# Generated by Django 2.2 on 2020-06-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('imageUrl', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='No Name', max_length=70)),
                ('fatherName', models.CharField(default='No Name', max_length=70)),
                ('deptName', models.CharField(default='No Name', max_length=70)),
                ('inchargeName', models.CharField(default='No Name', max_length=70)),
                ('contactNo', models.CharField(default='No Number', max_length=15)),
                ('bloodGroup', models.CharField(default='NA', max_length=5)),
                ('qualification', models.CharField(default='NA', max_length=50)),
            ],
        ),
    ]
