# Generated by Django 2.2 on 2020-07-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterExitInfo',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uid', models.IntegerField()),
                ('inTime', models.TimeField(auto_now_add=True)),
                ('outTime', models.TimeField()),
                ('diffTime', models.TimeField()),
                ('isIn', models.BooleanField()),
            ],
        ),
    ]
