# Generated by Django 2.2 on 2020-07-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_enterexitinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterexitinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
